import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/layout/layout'
import Header from '../components/header/header'
import Sidebar from '../components/sidebar/sidebar'

export default function Home() {
  return (
    <Layout title={"Team"}>
        <Head>
          <title>Webloom Assignment</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta
            property="og:image"
            content="webloom"
          />
          <meta name="og:title" content="webloon" />
          <meta name="twitter:card" content="summary_large_image" />
        </Head>
       
       
        <main>Home</main>
    </Layout>
  )
}
